<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>프라미스 객체에서 예외 위임</title>
</head>
<body>
    <h1>프라미스 객체에서 예외 위임</h1>
    <script>
        let e=new Error();
        //에러객체를 만든다고 오류가 발생하지 않는다.
        //throw e;
        let a=10;
        let b="이십!";
        new Promise((resolve, reject) => {
            let sum=(+a)+(+b); //NaN 가 아니면 resolve, NaN면 reject
            //isNaN(NaN일수도 있는 데이터) 검사
            //isNaN("십") 검사 =>true
            //Number.isNaN(NaN) 검사
            //Number.isNaN("십") 검사 =>false
            if(Number.isNaN(sum)){ //a나 b 둘중하나가 NaN
                //reject("a나 b 둘중하나가 NaN");
                throw new Error("NumberFormat : a나 b 둘중하나가 NaN")
            }else{
                resolve(sum);
            }
        }).then((sum)=>{
            console.log("a+b="+sum);
        }).catch(err=>{
            console.log("catch: "+err);
        })

    //async 함수에서 promise의 예외 처리
    const run=async(n1,n2)=>{
        try {
            let result = await new Promise((resolve, reject) => {
                let sum = (+n1) + (+n2);
                if (Number.isNaN(sum)) {
                    reject(new Error("reject n1,n2 둘중 NaN가 있습니다."));
                    //throw (new Error("throw n1,n2 둘중 NaN가 있습니다."));
                } else {
                    resolve(sum);
                }
            });
            console.log("run.result: ",result);
        }catch (e) {
            console.log(e)
        }
    };
    run(10,20);
    run("20",20);
    run("이십",20);
    console.log("안녕!")


    //async function run(){}


    </script>
</body>
</html>